[package]
name = "lurk-ipld-core"
version = "0.1.0"
authors = ["porcuquine <porcuquine@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Base traits and definitions used by ipld codecs."
repository = "https://github.com/lurk-lang/lurk-ipld"

[features]
default = ["std"]
std = ["anyhow/std", "cid/std", "multibase/std", "multihash/std", "thiserror"]
serde-codec = ["cid/serde-codec", "serde"]

[dependencies]
anyhow = { version = "1.0.40", default-features = false }
cid = { version = "0.8.3", default-features = false, features = ["alloc"] }
core2 = { version = "0.4", default-features = false, features = ["alloc"] }
multihash = { version = "0.16.0", default-features = false, features = ["alloc"] }

multibase = { version = "0.9.1", default-features = false, optional = true }
serde = { version = "1.0.132", default-features = false, features = ["alloc"], optional = true }
thiserror = {version = "1.0.25", optional = true }

[dev-dependencies]
multihash = { version = "0.16.0", default-features = false, features = ["multihash-impl", "blake3"] }
serde_test = "1.0.132"
serde_bytes = "0.11.5"
serde_json = "1.0.79"
